<?xml version="1.0" encoding="utf-8" ?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<!--
//*****************************************************************************
// Distributed under the GNU General Public Licence
//*****************************************************************************
-->
<xsl:template match="view">
    <xsl:choose>
        <xsl:when test="name = 'help'">
            <h2>Welcome!</h2>
            <p>The following reports are automatically generated by "<a href="http://en.wikipedia.org/wiki/Web_scraping">scraping</a>" the reservations in Cloudbeds on a daily basis.</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/reports/reservations-split-across-rooms</xsl:attribute>Reservations Split Across Rooms</a> - Includes any and all bookings <em>of the same room type</em> which are allocated into different rooms. This may also include group bookings where the same group are spread amongst the same room type. It also includes any bookings which are "unallocated", ie. no room assignment.</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/reports/unpaid-deposit-report</xsl:attribute>Unpaid Deposit Report</a> - These are all active bookings for Expedia or Booking.com where the amount due is the same as the total amount (ie. nothing has been paid). These bookings will need to be manually charged a deposit amount.</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/reports/group-bookings</xsl:attribute>Group Bookings</a> - Shows any bookings with X or more persons (configurable on the Reports Settings admin page).</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/reports/bedcounts</xsl:attribute>Bed Counts</a> - Includes daily counts of the number of beds which have been filled. The export function will allow you download the data as a CSV file.</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/reports/guest-comments</xsl:attribute>Guest Comments</a> - Shows comments made by guests at the time of booking; may also contain additional fluff. If there are any guest requests, you can action them and tick it off once you're done.</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/reports/bottom-bunks-report</xsl:attribute>Bottom Bunks Report</a> - Shows bookings with notes requesting a bottom bunk but one or more bunks are currently assigned to a top bunk.</p>

            <p><a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/housekeeping</xsl:attribute>Housekeeping</a> - Pretty straightforward. It does not include any long term dormitories - also any room closures ending on the day will be marked as "CHANGE" even if there is another room closure for the next day and a note saying to manually check this - since we use closures to mark cleaning hours.</p>

        </xsl:when>

        <xsl:when test="name = 'help_admin'">
            <a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/admin/report-settings</xsl:attribute>Report Settings</a> - Logins for all dependent sites and hostel-specific report settings.

            <a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/admin/job-history</xsl:attribute>Job History</a> - A list of jobs that have recently run.

            <a><xsl:attribute name="href"><xsl:value-of select="homeurl"/>/admin/job-scheduler</xsl:attribute>Job Scheduler</a> - Automated scheduled jobs.
        </xsl:when>

        <xsl:otherwise>
            Help page slug '<xsl:value-of select="name"/>' not recognised.
        </xsl:otherwise>
    </xsl:choose>
</xsl:template>

</xsl:stylesheet>